platform :ios,'8.0'
target 'FZImageHandle' do
	pod 'MJExtension'     
	pod 'MTBlockAlertView'
	pod 'MBProgressHUD'
	pod 'FMDB'
	pod 'PEPhotoCropEditor'
	pod 'TZImagePickerController', '~> 1.7.7'
    pod 'MJRefresh'
end
